version: '3.9'
services:
    # Complect Frontend
    complect-front:
        container_name: complect-front
        build: .
        image: complect-front:1.0
        ports:
            - 81:81 # Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev
        # command: tail -F anything
    


    ##### TMP Back ####
    # Complect
    complect-app:
        container_name: complect-app
        build:
            context: .
            dockerfile: _back/Dockerfile.dev
        image: complect-app:1.0
        ports:
            - 82:3000
        environment:
            HOST: 0.0.0.0
            JOB_WORKER_URL: redis://redis:6379/0
        volumes:
            - ./_back/:/complect
            - /complect/node_modules
        working_dir: /complect
        command: rails s
        depends_on:
            - redis
            - postgres

    # Redis
    redis:
        container_name: redis
        image: redis

    # Postgres
    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: _back/Dockerfile.db
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
        volumes:
            - ./_back/postgres/:/var/lib/postgresql/data/