version: '3.9'
services:
    # Complect Frontend
    complect-front:
        container_name: complect-front
        build: .
        image: complect-front:1.0
        ports:
            - 81:81 # Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev
        # command: tail -F anything